_BASE_: MPVSS-VSPW.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  WEIGHTS: "pretrained/vspw_model_final_swin_base.pth"   # modify for different model
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  MOTION:
    OUT_CHANNELS: [128, 256, 512, 1024]
OUTPUT_DIR: ../experiments/Mask2former/vspw/swin_base_attnflowformask
