_BASE_: MPVSS-VSPW.yaml
MODEL:
  WEIGHTS: "pretrained/vspw_r50_model_final.pth"  # "pretrained/vspw_r50_model_final.pth"   # modify for different model
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN"  # use syncbn for cityscapes dataset
    RES5_MULTI_GRID: [1, 1, 1]  # not used
OUTPUT_DIR: .output/vspw_PerAttnFlowQueryFMask-VSPW-R50