_BASE_: Base-VSPW-R50.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  WEIGHTS: "pretrained/swin_large_patch4_window12_384_22k.pkl"   # modify for different model
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 100
OUTPUT_DIR: ../experiments/Mask2former/cityscapes/swin_large
