_BASE_: Base-VSPW-R50.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  WEIGHTS: "pretrained/swin_base_patch4_window12_384_22k.pkl"   # modify for different model
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
OUTPUT_DIR: ../experiments/Mask2former/cityscapes/swin_base
